### ISSUE TITLE
Bungee support would be epic!

### ISSUE THREAD

**Issue by kelso6969** [sladkoff/minecraft-prometheus-exporter#15]
I know this sort of falls under multiple server support (open ticket), but the ability to have it run in one location, with a per server plugin for individual server tps, memory, etc. Bungee would be more of a total player count across the network along with what server they;re on.

Thanks!

**Comment by sladkoff** [comment]
Better answer later than never...

There are now instructions on how to configure this for multiple servers.

Basically, every one of your servers runs this plugin and exports the stats. Prometheus is configured to add a unique label to each of your servers during scraping. In Grafana you'll be able to identify the different servers by that label.

--- 

Unfortunately, I don't use Bungee so I don't know much about it. 

But what you're describing should be possible with some additional labels in the Prometheus scrape_config and with a custom Grafana dashboard.

For the scrape config you could go with something like this:

```yaml
- job_name: 'minecraft'
  static_configs:
    - targets: ['server1:9225']
      labels:
        server_name: 'server1' 
        bungee_group: 'bungee1'
    - targets: ['server2:9225']
      labels:
        server_name: 'server2'
        bungee_group: 'bungee1'
```

Note that the servers have a unique unique `sever_name` label and a common `bungee_group` which is meant to imply that they belong to one Bungee network.

In your custom Grafana dashboard, you can then get the total player count across the Bungee network with: `sum(mc_players_total{bungee_group="bungee1"})`.
