### ISSUE TITLE
[Feature Request] finished prometheus.yml with minecraft job added

### ISSUE THREAD

**Issue by toastydoctor** [sladkoff/minecraft-prometheus-exporter#28]
I can't seem to properly paste :

 - job_name: 'minecraft'
  static_configs:
    - targets: ['localhost:9225']
      labels:
        server_name: 'my-awesome-server'

into the config i keep getting indentation errors and :
line 14: field -targets not found in type config.plain\n  line 15: field labels not found in type config.plain\n

**Comment by sladkoff** [comment]
Documentation: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

Example Prometheus config: https://github.com/prometheus/prometheus/blob/release-2.15/config/testdata/conf.good.yml

Append the minecraft job to the `scrape_configs` section:

```yml
scrape_configs:
  - job_name: 'minecraft'
    static_configs:
      - targets: ['localhost:9225']
        labels:
          server_name: 'my-awesome-server'
```
