### ISSUE TITLE
[Question] HTTP Error Bad Gateway when adding to Grafana

### ISSUE THREAD

**Issue by kARAT97** [sladkoff/minecraft-prometheus-exporter#36]
I already have Grafana an Prometheus running monitoring the dedicated server itself, now I'm trying to add this exporter to monitor each minecraft server instance.
I've added the plugin to all servers and verified the port configuration on there along with restarting the servers.

I've configured the scrape config for Prometheus and it's like this:
```yaml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - first.rules
  # - second.rules

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'minecraft'
    static_configs:
      - targets: ['localhost:25578']
```

The servers are all hosted on the same machine as Prometheus and Grafana, I've tried opening the port outside through the firewall but it seems like grafana can't use the data source.

I've verified the plugin itself is working as I can access the data itself from http://46.4.72.117:25578/metrics

The servers are hosted on docker instances within the same dedicated box as grafana and prometheus.
